### ISSUE TITLE
Node.js dependency

### ISSUE THREAD

**Issue by si14** [sockjs/sockjs-erlang#10]
Guys, are you serious?

**Comment by majek** [comment]
Sockjs-erlang is using tests written as a part of sockjs/sockjs-client . 

You don't need node if you just want to use this project. You need node if you want to run sockjs tests against it.

**Comment by si14** [comment]
Don't you think about changing this? I mean get rid of node at all.

**Comment by majek** [comment]
The tests are part of sockjs-client, and live there. There is no point in copying them to this project.

**Comment by si14** [comment]
> There is no point

There is at least one.

> get rid of node

**Comment by majek** [comment]
Feel free to write a test suite for sockjs-erlang in erlang. We'll be happy to include it as a default action for `make test`.
