### ISSUE TITLE
Broadcast test not implemented

### ISSUE THREAD

**Issue by sinnus** [sockjs/sockjs-erlang#6]
1. Compile and start test server using `make test`
2. Make request using `http://localhost:8080/broadcast/077/p2fpxgt4d/xhr` or run smoketest for xhr-polling
3. The following error message in erl console:

```
=ERROR REPORT==== 1-Oct-2011::01:40:21 ===
    module: misultin_http
    line: 597
file not found
```

**Comment by majek** [comment]
SockJS-erlang is still quite experimental, in some places we did cut corners. Please do continue reporting bugs, we'll try to fix them soonish.

**Comment by majek** [comment]
Sinnus: the fix landed.

Simon, can you sanity check it?

**Comment by simonmacmullen** [comment]
Tidied slightly.
