### ISSUE TITLE
Qunit tests break on utf encoding

### ISSUE THREAD

**Issue by majek** [sockjs/sockjs-erlang#9]
Probably due to \0 issue with eep0018, introduced by @squaremo in 2423565395f4c6670f581006826196dda7719df5. That's not good. Any ideas? Should we ship mochjson or fix eep?

**Comment by squaremo** [comment]
Or this: https://github.com/jchris/erlang-json-eep-parser
which is the only one I've found that /actually/ implements eep0018. For the record.

**Comment by squaremo** [comment]
Options:
- distribute mochijson2 (and mochinum) if the license allows
- fork eep0018, fix the NUL issue, and depend on that
- (assuming jiffy does not have the NUL issue) depend on jiffy
- depend on erlang-rfc4627

Any votes?

**Comment by squaremo** [comment]
OK well I can report that erlang-rfc4627 appears to be too much trouble to have as a dependency. (Doesn't compile out of the box for me (can't find inets/include/httpd.hrl); comes with JSONRPC app).
Let's try jiffy.

**Comment by squaremo** [comment]
Jiffy passes all the tests. Hurrah. But it did require a new rebar to be put in the repo. (This appears to be not uncommon practice)

**Comment by majek** [comment]
I would like to hear if jiffy works/compiles on mac. Except for that it's fine for me.

**Comment by squaremo** [comment]
Yes, I was using a mac.

FTR there was another suggestion (that I had forgotten about): https://github.com/talentdeficit/jsx
Which is pure erlang, but looks unfinished.
